todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('task_create/', views.task_create, name='task_create'),
    path('task_update/<int:task_id>/', views.task_update, name='task_update'),
    path('task_delete/<int:task_id>/', views.task_delete, name='task_delete'),
]

todos/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_title = models.CharField(max_length=200)
    task_description = models.TextField(blank=True)
    is_completed = models.BooleanField(default=False)
    created_date = models.DateTimeField('date created', default=timezone.now)

    def __str__(self):
        return self.task_title

todos/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['task_title', 'task_description', 'is_completed']

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

from .models import Task
from .forms import TaskForm


def login_view(request):
    if request.user.is_authenticated:
        return redirect('todos:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('todos:index')
    else:
        form = AuthenticationForm()

    context = { 'form': form }
    return render(request, 'todos/login.html', context)


def register_view(request):
    if request.user.is_authenticated:
        return redirect('todos:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('todos:index')
    else:
        form = UserCreationForm()

    context = { 'form': form }
    return render(request, 'todos/register.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('todos:login')


@login_required
def index(request):
    task_list = Task.objects.order_by('is_completed', '-created_date')
    task_list = task_list.filter(user=request.user)
    incomplete_count = task_list.filter(is_completed=False).count()

    search_string = request.GET.get('search_string', '')
    if search_string:
        task_list = task_list.filter(task_title__icontains=search_string)

    context = {
        'task_list': task_list,
        'incomplete_count': incomplete_count,
        'search_string': search_string
    }
    return render(request, 'todos/index.html', context)


@login_required
def task_create(request):
    if request.method == 'POST':
        task = Task(user=request.user)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('todos:index')
    else:
        form = TaskForm()

    context = { 'form': form }
    return render(request, 'todos/task_form.html', context)


@login_required
def task_update(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('todos:index')
    else:
        form = TaskForm(instance=task)

    context = { 'form': form }
    return render(request, 'todos/task_form.html', context)


@login_required
def task_delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        task.delete()
        return redirect('todos:index')

    context = { 'task': task }
    return render(request, 'todos/task_delete.html', context)

todos/templates/todos/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>{% block title %}Todo-app{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'todos/favicon.ico' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Raleway&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'todos/style.css' %}">
  </head>
  <body>
    <div id="container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

todos/templates/todos/index.html
{% extends "todos/base.html" %}
{% block content%}

<div class="header-bar">
  <div>
    <h1>Hello {{ request.user|title }}</h1>
    <h3>You have <i>{{ incomplete_count }}</i> incomplete task{{ incomplete_count|pluralize }}</h3>
  </div>

  {% if request.user.is_authenticated %}
  <a href="{% url 'todos:logout' %}">Logout</a>
  {% else %}
  <a href="{% url 'todos:login' %}">Login</a>
  {% endif %}
</div>



<div id="search-add-wrapper">
  <form method="get" style="display: flex;">
    <input type="text" name="search_string" value="{{ search_string }}">
    <input class="button" type="submit" value="Search">
  </form>
  <a id="add-link" href="{% url 'todos:task_create' %}">&#x2b;</a>
</div>

<div class="task-list-wrapper">
  {% for task in task_list %}
  <div class="task-wrapper">
    <div class="task-title">
      {% if task.is_completed %}
      <div class="task-complete-icon"></div>
      <i><s><a href="{% url 'todos:task_update' task.id %}">{{ task }}</a></s></i>
      {% else %}
      <div class="task-incomplete-icon"></div>
      <a href="{% url 'todos:task_update' task.id %}">{{ task }}</a>
      {% endif %}
    </div>
    <a class="delete-link" href="{% url 'todos:task_delete' task.id %}">&#215;</a>
  </div>
  {% empty %}
  <h3 style="padding: 20px; text-align: center;">No items in the list</h3>
  {% endfor %}
</div>

{% endblock %}

todos/templates/todos/login.html
{% extends 'todos/base.html' %}
{% block content %}

<div class="header-bar">
  <h1>Login</h1>
</div>

<div class="card-body">
  <form method="post" action="{% url 'todos:login' %}">
    {% csrf_token %}
    {% comment %}{{ form.as_p }}{% endcomment %}

    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="field-wrapper">
        {{ field.label_tag }}
        {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
        <div class="helptext">{{ field.help_text|safe }}</div>
        {% endif %}
    </div>
    {% endfor %}

    <input class="button" type="submit" value="Login">
  </form>
  <p>Don't have an account? <a href="{% url 'todos:register' %}">Register</a></p>
</div>

{% endblock content %}

todos/templates/todos/register.html
{% extends 'todos/base.html' %}
{% block content %}

<div class="header-bar">
  <h1>Register</h1>
</div>

<div class="card-body">
  <form method="post" action="">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="field-wrapper">
        {{ field.label_tag }}
        {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
        <div class="helptext">{{ field.help_text|safe }}</div>
        {% endif %}
    </div>
    {% endfor %}

    <input class="button" type="submit" value="Register">
  </form>
  <p>Already have an account? <a href="{% url 'todos:login' %}">Login</a></p>
</div>

{% endblock content %}

todos/templates/todos/task_create.html
{% extends 'todos/base.html' %}
{% block content %}

<h3>Create task</h3>

<a href="{% url 'todos:index' %}">Back</a>

<form method="post" action="{% url 'todos:task_create' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock content %}

todos/templates/todos/task_delete.html
{% extends 'todos/base.html' %}
{% block content %}

<div class="header-bar">
  <a href="{% url 'todos:index' %}">&#8592; Back</a>
</div>

<div class="card-body">
  <form method="post" action="{% url 'todos:task_delete' task.id %}">
    {% csrf_token %}
    <p>Are you sure you want to delete this task? "{{ task }}"</p>
    <input class="button" type="submit" value="Delete">
  </form>
</div>

{% endblock content %}

todos/templates/todos/task_form.html
{% extends 'todos/base.html' %}
{% block content %}

<div class="header-bar">
  <a href="{% url 'todos:index' %}">&#8592; Back</a>
</div>

<div class="card-body">
  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="button" type="submit">
  </form>
</div>

{% endblock content %}